name: Deploy BlitzWrite Frontend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Production Environment Variables
      run: |
        echo "REACT_APP_API_URL=${{ secrets.PRODUCTION_API_URL }}" > .env

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.LIF_ID }}

    - name: Deploy to Server
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@133.242.160.145 << 'EOF'
          cd ~/blitzwrite/Blitzwrite_frontend
          git remote set-url origin git@github.com:lifcompany/Blitzwrite_frontend.git

          eval $(ssh-agent -s)
          ssh-add ~/.ssh/sm_automation.pem
          ssh-add -l

          git pull origin main
          
          cd ~/blitzwrite/Blitzwrite_frontend
          npm install
          npm run build
          sudo rsync -av --delete ~/blitzwrite/Blitzwrite_frontend/build/ /var/www/html/
          
          sudo systemctl restart nginx

          echo "Deployment completed."
        EOF
